server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  application:
    name: "nhnBaseCamp"
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  profiles:
    active: "local-db"
  servlet:
    multipart:
      enabled: true
    location: /Users/nhn/Documents/file
    max-request-size: 30MB
    max-file-size: 10MB

org:
  zerock:
    upload:
      path: /Users/nhn/Documents/file
---
spring:
  config:
    activate:
      on-profile: "local-db"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: "test"
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDB103Dialect
      ddl-auto: create